#ifndef STRINGS_H
#define STRINGS_H

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define Y_XVER 0x00010000

#define Y_VER_MAJOR ((Y_XVER & 0xFF000000)>>24)
#define Y_VER_MINOR ((Y_XVER & 0x00FF0000)>>16)
#define Y_VER_PATCH ((Y_XVER & 0x0000FF00)>>8)
#define Y_VER_BUILD (Y_XVER & 0x000000FF)

#define Y_VERSION STR(Y_VER_MAJOR) "." STR(Y_VER_MINOR) "." STR(Y_VER_PATCH) \
    "-" STR(Y_VER_BUILD)

// File types that can be added to a project
#define Y_PROJ_FTYPES \
	"Media files (*.mp4 *.m4v *.mov *.wav *.pcm *.aac *.flac *.srt *.ass);;" \
	"Video files (*.mp4 *.m4v *.mov);;" \
	"Audio files (*.wav *.pcm *.aac *.flac);;" \
	"Subtitles (*.srt *.ass);;" \
	"All files (*.*)"

// Yavicot projects
#define Y_YPRO_FTYPE \
	"Yavicot projects (*.ypro);;" \
    "All files (*.*)"

#define Y_YPRO_XMLCOMMENT "Generated by yavicot v" Y_VERSION

#define Y_UNNAMED_PROJ "Unnamed yavicot project"

#endif // STRINGS_H
